eventkulater/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :budgets

  post "newplayer" => "budgets#newplayer"

  get "add" =>"budgets#add"

end

eventkulater/app/models/budget.rb
class Budget < ActiveRecord::Base
end

eventkulater/app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:name, :event, :budget, :item, :no_item, :price, :photo_url, :website_add, :contact_info)
    end
end

eventkulater/app/helpers/budgets_helper.rb
module BudgetsHelper
end

eventkulater/app/views/budgets/_form.html.erb
<%= form_for(@budget) do |f| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% @budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enter_a_username %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :name_of_your_event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :what_is_your_budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="field">
<%= f.label :item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :how_many %><br>
    <%= f.number_field :no_item %>
  </div>
  <div class="field">
    <%= f.label :price_per_item %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :url_link_photo_of_item %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div class="field">
    <%= f.label :item_website %><br>
    <%= f.text_field :website_add %>
  </div>
  <div class="field">
    <%= f.label :contact_information %><br>
    <%= f.text_field :contact_info %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>    

eventkulater/app/views/budgets/add.html.erb
<div id="addMore"> 

<h1>Add more photos to BadLibs Breaking Midas</h1>

<form method="POST" action="/budgets">
  <p><%= budget.event %></p>
  <p><%= budget.budget %></p>
  <p><%= budget.item %></p>
  <p><%= budget.no_item %></p>
  <p><%= budget.price %></p>
  <p><%= budget.photo_url %></p>
  <p><%= budget.website_add %></p>
  <p><%= budget.contact_info %></p>
  <button>Save</button>
</form>

eventkulater/app/views/budgets/edit.html.erb
<h1>Update your list</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

eventkulater/app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>EVENTKULATER</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Event</th>
      <th>Budget</th>
      <th>Item</th>
      <th>No item</th>
      <th>Price</th>
      <th>photo</th>
      <th>Website add</th>
      <th>Contact info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.name %></td>
        <td><%= budget.event %></td>
        <td><%= budget.budget %></td>
        <td><%= budget.item %></td>
        <td><%= budget.no_item %></td>
        <td><%= budget.price %></td>
        <td><img src=<%= budget.photo_url %> height="50" width="50"></td>
        <td><%= budget.website_add %></td>
        <td><%= budget.contact_info %></td>
        <td><%= link_to 'Show', budget %></td>
        <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Planner Project', new_budget_path %>

eventkulater/app/views/budgets/new.html.erb
<h1> EVENTKULATER </h1>

<%= render 'form' %>

<%= link_to 'Back', budgets_path %>

eventkulater/app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>name:</strong>
  <%= @budget.name %>
</p>

<p>
  <strong>event:</strong>
  <%= @budget.event %>
</p>

<p>
  <strong>budget:</strong>
  <%= @budget.budget %>
</p>

<p>
  <strong>item:</strong>
  <%= @budget.item %>
</p>

<p>
  <strong>no_item:</strong>
  <%= @budget.no_item %>
</p>

<p>
  <strong>price:</strong>
  <%= @budget.price %>
</p>

<p>
  <strong>photo_url:</strong>
  <%= @budget.photo_url %>
</p>

<p>
  <strong>website_add:</strong>
  <%= @budget.website_add %>
</p>

<p>
  <strong>contact-info:</strong>
  <%= @budget.contact_info %>
</p>

<%= link_to 'Update', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>