prlast/config/routes.rb
Rails.application.routes.draw do
    resources :users do
  resources :planner_lists
end
root "users#index"

end

prlast/app/models/planner_list.rb
class PlannerList < ActiveRecord::Base
  belongs_to :user
end

prlast/app/models/user.rb
class User < ActiveRecord::Base
  has_many :planner_lists
end

prlast/app/controllers/planner_lists_controller.rb
class PlannerListsController < ApplicationController
  before_action :set_planner_list, only: [:show, :edit, :update, :destroy]

  # GET /planner_lists
  # GET /planner_lists.json
  def index
    @planner_lists = PlannerList.all
  end

  # GET /planner_lists/1
  # GET /planner_lists/1.json
  def show
  end

  # GET /planner_lists/new
  def new
    @planner_list = PlannerList.new
  end

  # GET /planner_lists/1/edit
  def edit
  end

  # POST /planner_lists
  # POST /planner_lists.json
  def create
    @planner_list = PlannerList.new(planner_list_params)

    respond_to do |format|
      if @planner_list.save
        format.html { redirect_to @planner_list, notice: 'Planner list was successfully created.' }
        format.json { render :show, status: :created, location: @planner_list }
      else
        format.html { render :new }
        format.json { render json: @planner_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planner_lists/1
  # PATCH/PUT /planner_lists/1.json
  def update
    respond_to do |format|
      if @planner_list.update(planner_list_params)
        format.html { redirect_to @planner_list, notice: 'Planner list was successfully updated.' }
        format.json { render :show, status: :ok, location: @planner_list }
      else
        format.html { render :edit }
        format.json { render json: @planner_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planner_lists/1
  # DELETE /planner_lists/1.json
  def destroy
    @planner_list.destroy
    respond_to do |format|
      format.html { redirect_to planner_lists_url, notice: 'Planner list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planner_list
      @planner_list = PlannerList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planner_list_params
      params.require(:planner_list).permit(:event, :budget, :user_id)
    end
end

prlast/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:enter_username)
    end
end

prlast/app/helpers/planner_lists_helper.rb
module PlannerListsHelper
end

prlast/app/helpers/users_helper.rb
module UsersHelper
end

prlast/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prlast</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

prlast/app/views/planner_lists/_form.html.erb
<%= form_for(@planner_list) do |f| %>
  <% if @planner_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@planner_list.errors.count, "error") %> prohibited this planner_list from being saved:</h2>

      <ul>
      <% @planner_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

prlast/app/views/planner_lists/edit.html.erb
<h1>Editing Planner List</h1>

<%= render 'form' %>

<%= link_to 'Show', @planner_list %> |
<%= link_to 'Back', planner_lists_path %>

prlast/app/views/planner_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Planner Lists</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Budget</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planner_lists.each do |planner_list| %>
      <tr>
        <td><%= planner_list.event %></td>
        <td><%= planner_list.budget %></td>
        <td><%= planner_list.user %></td>
        <td><%= link_to 'Show', planner_list %></td>
        <td><%= link_to 'Edit', edit_planner_list_path(planner_list) %></td>
        <td><%= link_to 'Destroy', planner_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Planner list', new_planner_list_path %>

prlast/app/views/planner_lists/new.html.erb
<h1>New Planner List</h1>

<%= render 'form' %>

<%= link_to 'Back', planner_lists_path %>

prlast/app/views/planner_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @planner_list.event %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @planner_list.budget %>
</p>

<p>
  <strong>User:</strong>
  <%= @planner_list.user %>
</p>

<%= link_to 'Edit', edit_planner_list_path(@planner_list) %> |
<%= link_to 'Back', planner_lists_path %>

prlast/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enter_username %><br>
    <%= f.text_field :enter_username %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

prlast/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

prlast/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Enter username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.enter_username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

prlast/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
<%= link_to 'start planning', new_planner_list_path %>

prlast/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Enter username:</strong>
  <%= @user.enter_username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>