coster/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :lists

end

coster/app/models/list.rb
class List < ActiveRecord::Base
end

coster/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

coster/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:item, :description, :photo, :contact, :cost)
    end
end

coster/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index
end
end

coster/app/helpers/application_helper.rb
module ApplicationHelper
end

coster/app/helpers/lists_helper.rb
module ListsHelper
end

coster/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventkulater</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

coster/app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :purchase_item %><br>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :add_a_photo_url %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :email_website_phone %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :total_cost %><br>
    <%= f.text_field :cost %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

coster/app/views/lists/edit.html.erb
<h1>Eventkulator</h1>
<h3>a purchase logger to track your event planning budget</h3>
<h5>make changes</h5>
<br>

<%= render 'form' %>
<br>

<%= link_to 'check your update', @list %> |
<%= link_to 'go back', lists_path %>

<%= link_to 'add more', new_list_path %>

coster/app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventkulator</h1>
<h3>a purchase logger to track your event planning budget</h3>

<br>

<table>
  <thead>
    <tr>
      <th>purchase</th>
      <th>description</th>
      <th>pic</th>
      <th>info</th>
      <th>total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= list.item %></td>
        <td><%= list.description %></td>
        <td><img src=<%= list.photo %> height="50" width="50"></td>
        <td><%= list.contact %></td>
        <td>$<%= list.cost %></td> 
        <td><%= link_to 'Show', list %></td>
        <td><%= link_to 'Edit', edit_list_path(list) %></td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'add to log of purchases for your event', new_list_path %>

coster/app/views/lists/new.html.erb
<h1>Eventkulator</h1>
<h2>a purchase logger to track your event planning budget</h2>
<h3>add items for the event</h3>
<br>


<%= render 'form' %>
<br>

<%= link_to 'See log of purchases', lists_path %>

coster/app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>purchase:</strong>
  <%= @list.item %>
</p>

<p>
  <strong>description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>pic:</strong>
  <%= @list.photo %>
</p>

<p>
  <strong>info:</strong>
  <%= @list.contact %>
</p>

<p>
  <strong>total:</strong>
  <%= @list.cost %>
</p>

<%= link_to 'make changes', edit_list_path(@list) %> |
<%= link_to 'check purchase log', lists_path %>